-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Campaign"
(
    company_name character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    goal numeric,
    pledged numeric,
    outcome character varying COLLATE pg_catalog."default",
    backers_count integer,
    country character(2) COLLATE pg_catalog."default",
    currency character(3) COLLATE pg_catalog."default",
    launched_date character varying(10) COLLATE pg_catalog."default",
    end_date character varying(10) COLLATE pg_catalog."default",
    category_id character varying(4) COLLATE pg_catalog."default",
    "sub-category_id" character varying COLLATE pg_catalog."default",
    cf_id integer,
    contact_id integer
);

CREATE TABLE IF NOT EXISTS public."Category"
(
    category_id character varying(4) COLLATE pg_catalog."default",
    category character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."Contacts"
(
    contact_id integer,
    "first name" character varying COLLATE pg_catalog."default",
    "last name" character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."Subcategory"
(
    "sub-category_id" character varying COLLATE pg_catalog."default",
    sub_category character varying COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public."Category"
    ADD FOREIGN KEY (category_id)
    REFERENCES public."Campaign" (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Contacts"
    ADD FOREIGN KEY (contact_id)
    REFERENCES public."Campaign" (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Subcategory"
    ADD FOREIGN KEY ("sub-category_id")
    REFERENCES public."Campaign" ("sub-category_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;